version: '3.8'

services:
  jela_svijeta_db_dev:
    image: postgres:14
    env_file: docker/.env
    restart: unless-stopped
    container_name: jela_svijeta_db
    ports:
      - "4163:5432"
    volumes:
      - jela_svijeta_volume:/var/lib/postgresql/data

volumes:
  jela_svijeta_volume:
    external: false
